import Head from 'next/head'
import Navbar from '../public/components/Navbar'
import HomePage from "./homePage"
import Services from "./services"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Design-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <HomePage />
      <Services />
      
    </div>
  )
}
